name: Screenshots-action Vercel

on:
  pull_request:
    branches:
      - development
      - master
    types:
      - opened

jobs:
  check-screen:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{ github.head_ref }}

      - name: vercel-preview-url
        uses: xxidbr9/vercel-preview-url@v1.0.10
        id: vercel_url
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        with:
          vercel_team_id: "xxidbr9"
          vercel_project_id: "prj_ALLlEBuMymBLuvT5yaB1NA4XZqsj"

      - name: screenshots-action
        uses: xxidbr9/screenshots-action@v1.1.18
        with:
          url: ${{ format('https://{0}/{1}', steps.vercel_url.outputs.preview_url, github.head_ref) }}
          devices: iPhone 12 Pro
          noDesktop: true

      - name: Upload Screenshots to Imgur
        id: upload
        uses: devicons/public-upload-to-imgur@v2.2.1
        with:
          path: ./screenshots/
          client_id: ${{secrets.IMGUR_CLIENT_ID}}

      - name: Make BOT Screenshots
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            # ✨ Ini hasil slicing mu 
            ${{ format('{0}{1}', env.blank-line, join(fromJSON(steps.upload.outputs.markdown_urls), ' ')) }}
            ${{format('creator : @{0}', github.actor)}}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
